name: workforce-scripts
channels:
  - esri-field-apps/label/workforce-beta
  - defaults
dependencies:
  - arcgis>=1.7.0
  - pip>=19.1.1
  - pendulum=1.4.4
  - python=3.7.0
  - seaborn=0.9.0
  - shapely=1.6.4
  - requests
  - configparser
  - pip:
      - pyqrcode==1.2.1
      - pypng==0.0.18
